"""Built-in G-code and M-code reference database."""

GCODE_DB = {

  # ─── MOTION ───────────────────────────────────────────
  "Motion": [
    ("G0",  "Rapid Move",
     "Move to position at maximum speed. No cutting/extrusion.",
     "G0 X10 Y20 Z5 F3000",
     "X Y Z A B C E F — target coords + feed rate"),
    ("G1",  "Linear Move",
     "Controlled linear motion at specified feed rate. Used for cutting/printing.",
     "G1 X50 Y30 Z-1 F800 E5",
     "X Y Z A B C E F — coords, feed, extrusion"),
    ("G2",  "Arc Move CW",
     "Clockwise arc move. I/J are offsets from start to center, R is radius.",
     "G2 X10 Y10 I5 J0 F500",
     "X Y Z I J R F E — endpoint, center offset or radius"),
    ("G3",  "Arc Move CCW",
     "Counter-clockwise arc move.",
     "G3 X10 Y10 I5 J0 F500",
     "X Y Z I J R F E — endpoint, center offset or radius"),
    ("G4",  "Dwell / Pause",
     "Pause motion for a defined time. S=seconds, P=milliseconds.",
     "G4 S2   ; pause 2 seconds\nG4 P500 ; pause 500ms",
     "S(seconds) P(milliseconds)"),
    ("G5",  "Bézier Cubic Spline",
     "Smooth cubic spline motion. Requires I J P Q control point offsets.",
     "G5 I0 J3 P0 Q-3 X10 Y20",
     "X Y I J P Q — endpoint and Bézier handles"),
    ("G6",  "Direct Stepper Move",
     "Low-level direct stepper position move (Marlin 2.x).",
     "G6 X1000 Y1000 F100",
     "X Y Z E I(sync) — raw step counts"),
    ("G12", "Clean Nozzle / Spindle",
     "Execute nozzle or tool cleaning cycle (if wiper hardware present).",
     "G12 P1 S1 T2",
     "P(pattern 0-2) S(strokes) T(triangles)"),
    ("G17", "XY Plane Select",
     "Select XY plane for arcs and canned cycles.",
     "G17","None"),
    ("G18", "XZ Plane Select",
     "Select XZ plane for arcs.",
     "G18","None"),
    ("G19", "YZ Plane Select",
     "Select YZ plane for arcs.",
     "G19","None"),
  ],

  # ─── COORDINATES ──────────────────────────────────────
  "Coordinates": [
    ("G20", "Inch Units",
     "Set all coordinates to inches.",
     "G20","None"),
    ("G21", "Millimeter Units",
     "Set all coordinates to millimeters (default).",
     "G21","None"),
    ("G53", "Move in Machine Coordinates",
     "Temporarily override workspace offsets for one move.",
     "G53 G0 X0 Y0","None"),
    ("G54", "Work Coordinate System 1",
     "Select WCS 1 (default workspace offset).",
     "G54","None"),
    ("G55", "Work Coordinate System 2","Select WCS 2.","G55","None"),
    ("G56", "Work Coordinate System 3","Select WCS 3.","G56","None"),
    ("G57", "Work Coordinate System 4","Select WCS 4.","G57","None"),
    ("G58", "Work Coordinate System 5","Select WCS 5.","G58","None"),
    ("G59", "Work Coordinate System 6","Select WCS 6.","G59","None"),
    ("G90", "Absolute Positioning",
     "All coordinates interpreted as absolute positions.",
     "G90","None"),
    ("G91", "Relative Positioning",
     "All coordinates interpreted relative to current position.",
     "G91","None"),
    ("G92", "Set Position / Offset",
     "Define current position as given coordinates without moving.",
     "G92 X0 Y0 Z0 E0",
     "X Y Z E A B C — new current position values"),
    ("G92.1","Reset Position Offsets",
     "Reset G92 offsets to zero.",
     "G92.1","None"),
    ("G92.2","Suspend Position Offsets",
     "Temporarily suspend G92 offsets.",
     "G92.2","None"),
    ("G92.3","Restore Position Offsets",
     "Restore previously suspended G92 offsets.",
     "G92.3","None"),
    ("G93", "Inverse Time Feed Mode",
     "Feed rate interpreted as fraction of move per minute.",
     "G93","None"),
    ("G94", "Units per Minute Feed Mode",
     "Feed rate in mm/min or in/min (default).",
     "G94","None"),
  ],

  # ─── HOMING ───────────────────────────────────────────
  "Homing": [
    ("G27", "Park Toolhead",
     "Move to park position defined in firmware.",
     "G27 P2",
     "P(raise: 0=no raise,1=raise if lower,2=always)"),
    ("G28", "Auto Home",
     "Home one or all axes. Without params homes all axes.",
     "G28       ; home all\nG28 X Y   ; home X and Y only\nG28 Z     ; home Z only",
     "X Y Z (optional) — axes to home"),
    ("G29", "Bed Leveling (Unified)",
     "Probe the bed for leveling. Behavior depends on firmware (bilinear, UBL, mesh).",
     "G29       ; full auto level\nG29 S1    ; UBL load slot 1\nG29 P1    ; UBL phase 1\nG29 A     ; activate",
     "S(slot) P(phase) A(activate) D(disable) L(load) T(trace) V(verbose)"),
    ("G29.1","Set Z Probe Offset",
     "Directly set the Z probe offset value.",
     "G29.1 Z-1.5",
     "Z — probe offset in mm"),
    ("G29.2","Enable/Disable Bed Leveling",
     "Toggle bed leveling compensation.",
     "G29.2 S1  ; enable\nG29.2 S0  ; disable",
     "S(1=enable, 0=disable)"),
    ("G30", "Single Z-Probe",
     "Probe Z at current XY position (or given XY) and report.",
     "G30\nG30 X50 Y50",
     "X Y (optional position to probe)"),
    ("G31", "Dock Sled / Set Probe Trigger",
     "Dock the Z probe sled or set probe trigger value.",
     "G31 P25 X-29 Y-29 Z0.5",
     "P(trigger) X Y Z(offset)"),
    ("G32", "Undock Sled / Probe Bed",
     "Undock the Z probe sled or probe the entire bed.",
     "G32","None"),
    ("G33", "Delta Auto Calibration",
     "Probe and auto-calibrate a delta printer geometry.",
     "G33 P4 C0.02",
     "P(probe points 3-10) C(precision) V(verbose)"),
    ("G34", "Z Steppers Auto-Align",
     "Use probe to automatically align multiple Z steppers.",
     "G34 I3 T0.02 A",
     "I(iterations) T(accuracy) A(amplification)"),
    ("G35", "Tramming Assistant",
     "Guide manual bed tramming using probe measurements.",
     "G35 S5.0",
     "S(screw pitch mm/rev)"),
    ("G38.2","Probe Toward Workpiece (Error)",
     "Move toward workpiece until probe triggers. Error if not triggered.",
     "G38.2 Z-10 F50","X Y Z F"),
    ("G38.3","Probe Toward Workpiece (No Error)",
     "Move toward workpiece until probe triggers or end of move.",
     "G38.3 Z-10 F50","X Y Z F"),
    ("G38.4","Probe Away from Workpiece (Error)",
     "Move away until probe releases. Error if already not triggered.",
     "G38.4 Z10 F50","X Y Z F"),
    ("G38.5","Probe Away from Workpiece (No Error)",
     "Move away until probe releases.",
     "G38.5 Z10 F50","X Y Z F"),
  ],

  # ─── BED LEVELING ─────────────────────────────────────
  "Bed Leveling": [
    ("M48",  "Probe Repeatability Test",
     "Probe Z repeatedly to test probe accuracy/repeatability.",
     "M48 P10 X100 Y100 V2 E L2",
     "P(probes) X Y V(verbose 0-4) E(engage) L(legs)"),
    ("M104", "Set Hotend Temperature (no wait)",
     "Set target hotend temp and continue without waiting.",
     "M104 S200","S(target °C) T(tool index)"),
    ("M190", "Wait for Bed Temperature",
     "Wait until bed reaches target temperature.",
     "M190 S60","S(target °C) R(below temp)"),
    ("M420", "Bed Leveling State",
     "Enable/disable bed leveling and optionally load/save mesh.",
     "M420 S1       ; enable\nM420 S0       ; disable\nM420 L1       ; load slot\nM420 V        ; report",
     "S(1=on,0=off) L(load slot) T(fade height) V(verbose)"),
    ("M421", "Set Mesh Value",
     "Manually set a single mesh bed leveling point.",
     "M421 I3 J2 Z0.15\nM421 X50 Y50 Z-0.12 N",
     "I J(grid indices) X Y(coords) Z(height) N(normalize)"),
    ("G26",  "Mesh Validation Pattern",
     "Print a pattern to visually validate mesh bed leveling.",
     "G26 C0.2 F200 H200 K1 L1.75 O10 P25 R4 S1.75 U10 X50 Y50",
     "C F H K L O P R S U X Y — many options, see docs"),
  ],

  # ─── BLTOUCH / PROBES ─────────────────────────────────
  "BLTouch": [
    ("M280", "Servo Position",
     "Set BLTouch/servo angle. BLTouch uses pin P0.\n"
     "  10° = push pin down (deploy)\n  90° = push pin down (touch mode)\n"
     "  120° = raise pin (stow)\n  160° = alarm release\n  60° = self-test",
     "M280 P0 S10   ; deploy probe\nM280 P0 S90   ; touch mode\nM280 P0 S120  ; stow probe\nM280 P0 S160  ; reset alarm\nM280 P0 S60   ; self test",
     "P(servo index, BLTouch=0) S(angle 0-180)"),
    ("M401", "Deploy Probe",
     "Deploy the Z probe (BLTouch, servo-based, or magnetic).",
     "M401","H(verbose)"),
    ("M402", "Stow Probe",
     "Retract/stow the Z probe.",
     "M402","None"),
    ("M48",  "Probe Accuracy Test",
     "Test BLTouch probe repeatability. Run after deployment.",
     "M48 P10 V2","P(count) V(verbose) E(engage each)"),
    ("M851", "XYZ Probe Offset",
     "Set the X/Y/Z offset of the probe (BLTouch) from the nozzle tip.",
     "M851 X-44 Y-14 Z-2.45",
     "X Y Z — offset in mm from nozzle"),
    ("G29",  "Auto Bed Leveling",
     "Run full auto bed level using BLTouch. Probes a grid and saves mesh.",
     "G29\nG29 V2  ; verbose output",
     "See Homing section for full G29 params"),
    ("M500", "Save BLTouch Offset to EEPROM",
     "After setting M851, save to EEPROM so it persists after reboot.",
     "M851 X-44 Y-14 Z-2.45\nM500",
     "None — saves all settings"),
    ("M503", "Report Settings (verify probe)",
     "Report all current settings including probe offsets.",
     "M503 S0","S(1=no comment)"),
    ("BLTOUCH_DEPLOY",  "BLTouch Deploy Sequence",
     "Complete sequence: deploy, probe, stow. Use as template.",
     "M280 P0 S10   ; deploy\nG4 P100        ; wait 100ms\nG30            ; probe at current XY\nM280 P0 S120  ; stow",
     "Template — not a single command"),
    ("BLTOUCH_RESET",   "BLTouch Alarm Reset",
     "Reset BLTouch after alarm/error state (flashing red LED).",
     "M280 P0 S160  ; alarm release\nG4 P100\nM280 P0 S120  ; stow",
     "Template — not a single command"),
  ],

  # ─── EXTERNAL SENSORS ─────────────────────────────────
  "Sensors": [
    ("M119", "Endstop States",
     "Report the current state of all endstops and probes.",
     "M119","None"),
    ("M43",  "Pin Debug / Endstop Monitor",
     "Watch pin states in real time, test servo, report endstops.",
     "M43          ; report all pins\nM43 P44 W    ; watch pin 44\nM43 E        ; endstop monitor\nM43 S        ; servo test",
     "P(pin) W(watch) E(endstops) S(servo) I(inverse) R(release)"),
    ("M145", "Set Material Preset",
     "Store temperature presets for material slots.",
     "M145 S0 H195 B45 F0",
     "S(material 0=PLA,1=ABS) H(hotend) B(bed) F(fan)"),
    ("M301", "Set PID Hotend",
     "Set PID tuning values for hotend temperature control.",
     "M301 P22.2 I1.08 D114",
     "P I D — PID constants; E(extruder index)"),
    ("M303", "PID Autotune",
     "Run PID autotune cycle for hotend or bed.",
     "M303 E0 S200 C8  ; hotend autotune at 200°C x8 cycles\nM303 E-1 S60 C8 ; bed autotune",
     "E(0=hotend,-1=bed) S(target °C) C(cycles) U(update)"),
    ("M304", "Set PID Bed",
     "Set PID tuning values for heated bed.",
     "M304 P10.0 I0.023 D305.4",
     "P I D — PID constants"),
    ("M305", "Set Thermistor Parameters",
     "Configure thermistor type and values.",
     "M305 P0 T100000 B4092 R4700",
     "P(sensor) T(resistance) B(beta) R(pullup)"),
    ("M400", "Finish Moves",
     "Wait until all moves in the planner buffer are complete.",
     "M400","None"),
    ("M406", "Filament Sensor Enable",
     "Enable filament presence/runout sensor.",
     "M406","None"),
    ("M407", "Filament Sensor Disable",
     "Disable filament presence/runout sensor.",
     "M407","None"),
    ("M412", "Filament Runout Sensor",
     "Enable/disable filament runout sensor and set distance.",
     "M412 S1 D25  ; enable, 25mm detect distance",
     "S(1=enable) D(distance mm) H(host handling)"),
    ("M600", "Filament Change Pause",
     "Pause print for filament change. Parks head and unloads.",
     "M600 X10 Y10 Z20 E-5 L50 U50",
     "X Y Z(park) E(retract) L(load length) U(resume load)"),
    ("M701", "Load Filament",
     "Run filament load sequence.",
     "M701 T0 L50 Z10",
     "T(tool) L(length mm) Z(raise mm) S(temp)"),
    ("M702", "Unload Filament",
     "Run filament unload sequence.",
     "M702 T0 U80 Z10",
     "T(tool) U(length mm) Z(raise mm)"),
  ],

  # ─── TEMPERATURE ──────────────────────────────────────
  "Temperature": [
    ("M104", "Set Hotend Temp (no wait)",
     "Set hotend target temperature and continue.",
     "M104 S200 T0","S(°C) T(tool 0-3)"),
    ("M105", "Report Temperatures",
     "Query and report all current temperatures.",
     "M105","None"),
    ("M106", "Set Fan Speed",
     "Set cooling fan speed. S0=off, S255=full.",
     "M106 S255 P0","S(0-255) P(fan index)"),
    ("M107", "Fan Off",
     "Turn off print cooling fan.",
     "M107 P0","P(fan index, optional)"),
    ("M109", "Wait for Hotend Temp",
     "Set hotend temp and wait until reached.",
     "M109 S200 T0","S(°C) T(tool) R(exact temp)"),
    ("M110", "Set Line Number",
     "Reset line number counter for checksums.",
     "M110 N0","N(line number)"),
    ("M140", "Set Bed Temp (no wait)",
     "Set heated bed target temperature and continue.",
     "M140 S60","S(°C)"),
    ("M141", "Set Chamber Temp (no wait)",
     "Set heated chamber target temperature.",
     "M141 S40","S(°C)"),
    ("M143", "Set Max Hotend Temp",
     "Set maximum allowed hotend temperature.",
     "M143 S275","S(°C)"),
    ("M155", "Temperature Auto-Report",
     "Automatically report temperatures every N seconds.",
     "M155 S4  ; every 4 seconds\nM155 S0  ; disable",
     "S(interval in seconds, 0=disable)"),
    ("M190", "Wait for Bed Temp",
     "Set bed temp and wait until reached.",
     "M190 S60","S(°C) R(below temp)"),
    ("M191", "Wait for Chamber Temp",
     "Set chamber temp and wait until reached.",
     "M191 S40","S(°C) R(below temp)"),
    ("M302", "Cold Extrude Allow",
     "Allow or prevent extrusion below minimum temperature.",
     "M302 S0   ; allow cold extrude\nM302 S170 ; set min to 170°C",
     "S(min temp, 0=allow always)"),
  ],

  # ─── FANS ─────────────────────────────────────────────
  "Fans": [
    ("M106", "Set Fan Speed",
     "Control fan speed by index. S0=off, S255=100%.",
     "M106 S128 P0  ; fan 0 at 50%\nM106 S255 P1  ; fan 1 at 100%",
     "S(0-255) P(fan index 0-2) T(extruder index)"),
    ("M107", "Fan Off",
     "Turn off fan completely.",
     "M107\nM107 P1","P(fan index)"),
    ("M710", "Controller Fan Settings",
     "Set controller board fan speed and idle timeout.",
     "M710 S255 I128 D60 A1",
     "S(active speed) I(idle speed) D(idle delay) A(auto)"),
  ],

  # ─── SPINDLE / LASER ──────────────────────────────────
  "Spindle": [
    ("M3",  "Spindle CW / Laser On",
     "Start spindle clockwise or enable laser. S=RPM or power.",
     "M3 S8000   ; 8000 RPM\nM3 S100    ; laser 100 power",
     "S(RPM or power 0-255)"),
    ("M4",  "Spindle CCW / Laser Dynamic",
     "Start spindle counter-clockwise. Laser dynamic mode.",
     "M4 S8000","S(RPM or power)"),
    ("M5",  "Spindle/Laser Off",
     "Stop spindle or turn off laser.",
     "M5","None"),
    ("M7",  "Mist Coolant On",
     "Turn on mist coolant (CNC).",
     "M7","None"),
    ("M8",  "Flood Coolant On",
     "Turn on flood coolant (CNC).",
     "M8","None"),
    ("M9",  "Coolant Off",
     "Turn off all coolant.",
     "M9","None"),
    ("M10", "Vacuum/Blower On",
     "Turn on vacuum or blower (CNC dust collection).",
     "M10","None"),
    ("M11", "Vacuum/Blower Off",
     "Turn off vacuum/blower.",
     "M11","None"),
    ("M3.1","Laser Fire",
     "Fire laser at given power for inline engraving.",
     "M3.1 S128","S(0-255 power)"),
    ("M5.1","Laser Stop",
     "Stop laser inline mode.",
     "M5.1","None"),
  ],

  # ─── LASER ────────────────────────────────────────────
  "Laser": [
    ("M3",  "Laser On (constant)",
     "Enable laser in constant power mode.",
     "M3 S200","S(power 0-255)"),
    ("M4",  "Laser On (dynamic)",
     "Enable laser in dynamic power mode (power scales with speed).",
     "M4 S200","S(max power)"),
    ("M5",  "Laser Off",
     "Disable laser.",
     "M5","None"),
    ("M106","Air Assist Fan",
     "Control air assist fan for laser cutting.",
     "M106 S255 P2","S(speed) P(fan index)"),
    ("G0",  "Laser Rapid Move (off)",
     "Rapid move with laser off (travel).",
     "G0 X100 Y100 F6000","X Y F"),
    ("G1",  "Laser Cut Move",
     "Move with laser on at controlled feed rate.",
     "G1 X200 F1500 S200","X Y F S(power)"),
    ("M7",  "Mist (Air) On",
     "Turn on air assist (mapped to mist coolant).",
     "M7","None"),
    ("M9",  "Air Assist Off",
     "Turn off air assist.",
     "M9","None"),
    ("M3.9","Laser Inline Enable",
     "Enable inline laser power control per-segment.",
     "M3.9","None"),
  ],

  # ─── EXTRUDER ─────────────────────────────────────────
  "Extruder": [
    ("T0",  "Select Tool 0",
     "Switch to extruder/tool 0.",
     "T0","None"),
    ("T1",  "Select Tool 1",
     "Switch to extruder/tool 1 (dual extrusion).",
     "T1","None"),
    ("M82", "Absolute Extrusion",
     "Set extruder to absolute mode.",
     "M82","None"),
    ("M83", "Relative Extrusion",
     "Set extruder to relative mode.",
     "M83","None"),
    ("M207","Set Retraction",
     "Configure firmware retraction settings.",
     "M207 S3 F45 Z0.2 W3",
     "S(length mm) F(speed mm/min) Z(lift mm) W(extra restart)"),
    ("M208","Set Retraction Recover",
     "Configure extra length/speed on retraction recovery.",
     "M208 S0 F10","S(extra mm) F(speed mm/min)"),
    ("M209","Auto Retract Enable",
     "Enable or disable firmware automatic retraction.",
     "M209 S1  ; enable\nM209 S0  ; disable",
     "S(1=enable, 0=disable)"),
    ("G10", "Retract",
     "Firmware retract using M207 settings.",
     "G10","None"),
    ("G11", "Recover (Unretract)",
     "Firmware retraction recover using M208 settings.",
     "G11","None"),
    ("M900","Linear Advance K Factor",
     "Set Linear Advance K factor for pressure equalization.",
     "M900 K0.2  ; typical PLA\nM900 K0    ; disable",
     "K(factor 0=disable)"),
  ],

  # ─── STEPPER MOTORS ───────────────────────────────────
  "Stepper": [
    ("M17",  "Enable All Steppers",
     "Energize all stepper motors.",
     "M17","None"),
    ("M18",  "Disable All Steppers",
     "De-energize all stepper motors (same as M84).",
     "M18","None"),
    ("M84",  "Disable Steppers",
     "Disable one or all stepper motors after inactivity timeout.",
     "M84       ; disable all\nM84 X Y   ; disable X and Y only\nM84 S30   ; set timeout 30s",
     "X Y Z E (axes) S(timeout seconds)"),
    ("M85",  "Inactivity Timeout",
     "Set stepper motor inactivity timeout.",
     "M85 S120","S(seconds, 0=disable)"),
    ("M92",  "Set Steps/mm",
     "Set stepper steps per mm for each axis.",
     "M92 X80 Y80 Z400 E97",
     "X Y Z E A B — steps/mm per axis"),
    ("M201", "Set Max Acceleration",
     "Set maximum acceleration for each axis (mm/s²).",
     "M201 X500 Y500 Z100 E5000",
     "X Y Z E A B — mm/s² per axis"),
    ("M202", "Set Max Travel Acceleration",
     "Set max acceleration for non-printing travel moves.",
     "M202 X500 Y500","X Y Z E — mm/s²"),
    ("M203", "Set Max Feedrate",
     "Set maximum feed rate (mm/s) per axis.",
     "M203 X200 Y200 Z10 E50",
     "X Y Z E A B — mm/s per axis"),
    ("M204", "Set Starting Acceleration",
     "Set default print (P) and travel (T) acceleration.",
     "M204 P800 T2000","P(print mm/s²) T(travel mm/s²) R(retract)"),
    ("M205", "Set Advanced Settings",
     "Set jerk, junction deviation, and minimum speeds.",
     "M205 X8 Y8 Z0.4 E2 S0.1 T0.1",
     "X Y Z E(jerk) S(min seg speed) T(min travel speed) J(junction dev)"),
    ("M211", "Software Endstops",
     "Enable/disable software endstop limits.",
     "M211 S1  ; enable\nM211 S0  ; disable",
     "S(1=enable, 0=disable)"),
    ("M350", "Set Microstepping",
     "Set microstepping divisor for each axis driver.",
     "M350 X16 Y16 Z16 E16 B1",
     "X Y Z E B(for each driver) — divisor"),
    ("M351", "Set Microstep Pins",
     "Directly set MS1/MS2 pins for microstepping.",
     "M351 X1 Y1 E1 B0 S1",
     "X Y Z E B(pin values) S(pin number 1 or 2)"),
    ("M569", "Driver Direction",
     "Reverse motor direction for a given axis driver.",
     "M569 S1 X  ; reverse X\nM569 S0 Y  ; normal Y",
     "S(0=normal,1=reverse) X Y Z E"),
    ("M906", "Set Motor Current (mA)",
     "Set stepper motor current via TMC drivers.",
     "M906 X800 Y800 Z800 E500",
     "X Y Z E A B — milliamps"),
    ("M911", "TMC Stealth Chop Thresh",
     "Report/set TMC stepper StealthChop velocity threshold.",
     "M911","None"),
    ("M912", "Clear TMC OT Flag",
     "Clear TMC driver overtemperature pre-warning flag.",
     "M912 X Y","X Y Z E (axes)"),
    ("M913", "Set Hybrid Threshold",
     "Set TMC hybrid SpreadCycle/StealthChop velocity threshold.",
     "M913 X100 Y100 Z3","X Y Z E — mm/s threshold"),
    ("M914", "TMC Bump Sensitivity",
     "Set sensorless homing stall sensitivity (TMC2209/2130).",
     "M914 X63 Y63","X Y Z — sensitivity -64 to 63"),
    ("M919", "TMC Chopper Timing",
     "Set custom chopper timing for TMC drivers.",
     "M919 O5 P3 S1 X","O P S axis"),
  ],

  # ─── EEPROM ───────────────────────────────────────────
  "EEPROM": [
    ("M500", "Save Settings",
     "Save all current settings to EEPROM.",
     "M500","None"),
    ("M501", "Load Settings",
     "Load settings from EEPROM (restore saved).",
     "M501","None"),
    ("M502", "Reset to Factory",
     "Reset all settings to compiled firmware defaults. Use M500 to save.",
     "M502\nM500  ; then save",
     "None"),
    ("M503", "Report Settings",
     "Print all current settings as G-code (can copy to restore).",
     "M503\nM503 S0  ; brief",
     "S(1=with comments, 0=no comments)"),
    ("M504", "Validate EEPROM",
     "Validate EEPROM data integrity.",
     "M504","None"),
  ],

  # ─── DISPLAY / LCD ────────────────────────────────────
  "Display": [
    ("M0",   "Unconditional Stop",
     "Pause and wait for user button press on LCD.",
     "M0\nM0 Click to continue\nM0 P5000 ; timeout 5s",
     "P(ms timeout) S(message)"),
    ("M1",   "Conditional Stop",
     "Stop if LCD or host allows, else continue.",
     "M1 Check filament","Message string (optional)"),
    ("M117", "Set LCD Message",
     "Display a message on the LCD screen.",
     'M117 Printing...\nM117 Done!',
     "Message text (max ~20 chars)"),
    ("M118", "Serial Print",
     "Print a message to the serial port / host.",
     'M118 Hello from printer\nM118 E1 ; to host',
     "A(action) E(echo) Pn(port) — message text"),
    ("M150", "Set LED Color",
     "Set RGB(W) LED color. Used for NeoPixel and RGB strips.",
     "M150 R255 G0 B0    ; red\nM150 R0 G255 B0  ; green\nM150 W128        ; warm white",
     "R G B W(white) P(neo index) I(index) K(keep)"),
    ("M300", "Play Tone / Beep",
     "Play a tone through the buzzer.",
     "M300 S440 P500  ; A4 for 500ms\nM300 S0 P100    ; silent pause",
     "S(freq Hz) P(duration ms)"),
    ("M73",  "Set Print Progress",
     "Set the print progress percentage and time remaining on LCD.",
     "M73 P50 R30  ; 50% done, 30 min remain",
     "P(percent 0-100) R(minutes remaining)"),
  ],

  # ─── SD CARD ──────────────────────────────────────────
  "SD Card": [
    ("M20",  "List SD Files",
     "List all files on the SD card.",
     "M20","None"),
    ("M21",  "Init SD Card",
     "Initialize / re-mount the SD card.",
     "M21","None"),
    ("M22",  "Release SD Card",
     "Release / unmount the SD card.",
     "M22","None"),
    ("M23",  "Select SD File",
     "Select a file for printing.",
     "M23 test.gcode","Filename (8.3 format)"),
    ("M24",  "Start/Resume SD Print",
     "Start or resume printing the selected SD file.",
     "M24\nM24 S100 T30","S(position) T(time)"),
    ("M25",  "Pause SD Print",
     "Pause the current SD print.",
     "M25","None"),
    ("M26",  "Set SD Position",
     "Set SD read position in bytes.",
     "M26 S10000","S(byte position)"),
    ("M27",  "SD Print Status",
     "Report SD print status and progress.",
     "M27\nM27 S4  ; auto-report every 4s",
     "S(interval seconds)"),
    ("M28",  "Start SD Write",
     "Open a file on SD for writing.",
     "M28 test.gcode","Filename"),
    ("M29",  "Stop SD Write",
     "Close the file being written to SD.",
     "M29","None"),
    ("M30",  "Delete SD File",
     "Delete a file from the SD card.",
     "M30 test.gcode","Filename"),
    ("M32",  "Select and Start Print",
     "Select file and start printing in one command.",
     "M32 test.gcode","Filename (supports subdirs)"),
    ("M33",  "Long Path to 8.3 Name",
     "Convert long filename to 8.3 DOS format.",
     "M33 /folder/mylong.gcode","Path"),
    ("M34",  "SD Card Sort Order",
     "Set SD card file sorting options.",
     "M34 S1 F1","S(1=alpha) F(1=folders first)"),
  ],

  # ─── CONTROL ──────────────────────────────────────────
  "Control": [
    ("M0",   "Unconditional Stop",
     "Halt machine and wait for user resume.",
     "M0","None"),
    ("M1",   "Conditional Stop",
     "Stop if SD printing.",
     "M1","None"),
    ("M2",   "Program End",
     "Indicate end of program (same as M30 in some firmware).",
     "M2","None"),
    ("M30",  "Program End / Delete File",
     "End program. In Marlin: delete SD file.",
     "M30","Filename (for delete)"),
    ("M112", "Emergency Stop",
     "Immediately stop all motion and shut down. Requires power cycle or firmware reset.",
     "M112","None"),
    ("M113", "Host Keepalive",
     "Set host keepalive interval.",
     "M113 S2","S(seconds, 0=disable)"),
    ("M115", "Firmware Info",
     "Report firmware version and capabilities.",
     "M115","None"),
    ("M116", "Wait for Temperatures",
     "Wait until all set temperatures are reached.",
     "M116","None"),
    ("M120", "Enable Endstops",
     "Enable endstop checking.",
     "M120","None"),
    ("M121", "Disable Endstops",
     "Disable endstop checking.",
     "M121","None"),
    ("M122", "TMC Debug Report",
     "Report TMC stepper driver debug information.",
     "M122","X Y Z E (optional)"),
    ("M226", "Wait for Pin State",
     "Wait until a pin is in the expected state.",
     "M226 P10 S1  ; wait for pin 10 HIGH",
     "P(pin) S(state 0=low,1=high)"),
    ("M355", "Case Light",
     "Toggle or set brightness of enclosure/case light.",
     "M355 S1 P128  ; on at 50%",
     "S(0=off,1=on) P(brightness 0-255)"),
    ("M380", "Activate Solenoid",
     "Activate the solenoid on the active extruder.",
     "M380","None"),
    ("M381", "Deactivate Solenoids",
     "Deactivate all solenoids.",
     "M381","None"),
    ("M410", "Quick Stop",
     "Stop all motion immediately (less severe than M112).",
     "M410","None"),
    ("M605", "Multi-Nozzle Mode",
     "Set dual-nozzle print mode (IDEX printers).",
     "M605 S2 R0 X20  ; mirror mode\nM605 S1         ; normal",
     "S(mode 0-3) X(offset) R(temp diff)"),
    ("M993", "SD to SPI Flash",
     "Copy SD card file to SPI flash.",
     "M993","None"),
    ("M994", "SPI Flash to SD",
     "Copy SPI flash to SD card.",
     "M994","None"),
  ],

  # ─── FILAMENT SENSOR ──────────────────────────────────
  "Filament": [
    ("M406", "Filament Sensor Enable",
     "Enable the filament presence sensor.",
     "M406","None"),
    ("M407", "Filament Sensor Disable",
     "Disable the filament presence sensor.",
     "M407","None"),
    ("M412", "Filament Runout",
     "Configure filament runout sensor.",
     "M412 S1 D25\nM412 R  ; report",
     "S(1=enable) D(detect distance mm) H(host response)"),
    ("M600", "Filament Change",
     "Pause for filament change. Parks, unloads, waits, reloads.",
     "M600\nM600 X10 Y10 Z5 E-3 L100",
     "X Y Z(park pos) E(retract) L(load) U(extra)"),
    ("M701", "Load Filament",
     "Load filament to nozzle.",
     "M701 T0 L120 Z5 S210",
     "T(tool) L(mm) Z(lift mm) S(temp)"),
    ("M702", "Unload Filament",
     "Unload filament from nozzle.",
     "M702 T0 U150 Z5",
     "T(tool) U(mm) Z(lift mm)"),
    ("M603", "Configure Filament Change",
     "Set filament change load/unload distances.",
     "M603 L100 U120",
     "L(load mm) U(unload mm) T(tool)"),
  ],

  # ─── POWER ────────────────────────────────────────────
  "Power": [
    ("M80",  "ATX Power On",
     "Turn on the ATX power supply (if controlled by firmware).",
     "M80","None"),
    ("M81",  "ATX Power Off",
     "Turn off the ATX power supply.",
     "M81","None"),
    ("M850", "Hotend Offset",
     "Set hotend XYZ offsets (multi-extruder).",
     "M850 X0.0 Y0.0 Z0.0","X Y Z — offset in mm"),
    ("M911", "TMC Stealth Chop Report",
     "Report TMC driver StealthChop status.",
     "M911","None"),
    ("M916", "TMC Z Raise on Stall",
     "Raise Z when stall detected (sensorless).",
     "M916","None"),
    ("M917", "TMC Min Current Find",
     "Find minimum motor current (TMC).",
     "M917 X Y","axes"),
    ("M918", "TMC Max Speed Find",
     "Find maximum speed before stall (TMC).",
     "M918","None"),
  ],

  # ─── DEBUG ────────────────────────────────────────────
  "Debug": [
    ("M111", "Debug Level",
     "Set debug flags. Sum of: 1=echo,2=info,4=errors,8=dryrun,16=comms,32=leveling.",
     "M111 S6   ; info + errors\nM111 S0   ; off",
     "S(flags bitmask)"),
    ("M114", "Get Position",
     "Report current position of all axes.",
     "M114\nM114 D  ; detailed\nM114 E  ; extended",
     "D(detailed) E(extended) R(realtime)"),
    ("M115", "Firmware Info",
     "Report firmware name, version, and capabilities (CAPS).",
     "M115","None"),
    ("M119", "Endstop States",
     "Report triggered/open state of all endstops.",
     "M119","None"),
    ("M122", "TMC Debug",
     "Detailed TMC stepper driver diagnostics.",
     "M122","X Y Z E axes (optional)"),
    ("M154", "Position Auto-Report",
     "Automatically report position every N seconds.",
     "M154 S4  ; every 4s\nM154 S0  ; disable",
     "S(interval seconds)"),
    ("M163", "Mix Factor",
     "Set proportional mix factor for mixing extruder.",
     "M163 S0 P0.5","S(component) P(mix 0-1)"),
    ("M164", "Save Mix",
     "Save current mix as a virtual tool.",
     "M164 S0","S(virtual tool index)"),
    ("M200", "Set Filament Diameter",
     "Set actual filament diameter for volumetric extrusion.",
     "M200 D1.75 T0\nM200 D0    ; disable volumetric",
     "D(mm) T(tool)"),
    ("M222", "Set Speed for Purpose",
     "Set extrusion factor percentage.",
     "M222 S95","S(percent)"),
    ("M404", "Filament Width Nominal",
     "Set nominal filament width and enable sensor reporting.",
     "M404 N1.75 W1","N(nominal mm) W(enable sensor)"),
    ("M408", "JSON Status Report",
     "Report machine status in JSON format (RepRapFirmware).",
     "M408 S0","S(type 0-5)"),
    ("M530", "Print Job Start",
     "Notify host of print job start with filename.",
     "M530 S1 L:filename.gcode","S(1=start) L(filename)"),
    ("M531", "Print Job Filename",
     "Set print job filename.",
     "M531 filename.gcode","Filename"),
    ("M532", "Print Job Progress",
     "Set print job progress percentage.",
     "M532 X50.0 L100000","X(percent) L(byte)"),
  ],

  # ─── CNC SPECIFIC ─────────────────────────────────────
  "CNC Specific": [
    ("G40", "Cutter Compensation Off",
     "Cancel cutter radius/diameter compensation.",
     "G40","None"),
    ("G41", "Cutter Comp Left",
     "Tool radius compensation to the left of programmed path.",
     "G41 D0.5","D(radius offset)"),
    ("G42", "Cutter Comp Right",
     "Tool radius compensation to the right of programmed path.",
     "G42 D0.5","D(radius offset)"),
    ("G43", "Tool Length Offset +",
     "Apply tool length offset (add).",
     "G43 H1","H(tool offset register 1-99)"),
    ("G44", "Tool Length Offset -",
     "Apply tool length offset (subtract).",
     "G44 H1","H(tool offset register)"),
    ("G49", "Cancel Tool Length Offset",
     "Cancel active tool length offset.",
     "G49","None"),
    ("G61", "Exact Path Mode",
     "Exact stop at each programmed point.",
     "G61","None"),
    ("G64", "Continuous Path Mode",
     "Continuous path blending (default for most).",
     "G64 P0.01","P(tolerance mm)"),
    ("G73", "Peck Drilling Cycle",
     "Canned peck drilling cycle with chip break.",
     "G73 X10 Y10 Z-20 R2 Q5 F100",
     "X Y(pos) Z(depth) R(retract) Q(peck) F(feed)"),
    ("G74", "Left-Hand Tapping Cycle",
     "CCW tapping canned cycle.",
     "G74 X10 Y10 Z-15 R2 F200","X Y Z R F"),
    ("G76", "Fine Boring Cycle",
     "Fine boring canned cycle.",
     "G76 X10 Y10 Z-10 R2 F50","X Y Z R F P Q"),
    ("G80", "Cancel Canned Cycle",
     "Cancel any active canned machining cycle.",
     "G80","None"),
    ("G81", "Drilling Cycle",
     "Simple drilling canned cycle.",
     "G81 X10 Y10 Z-20 R2 F100","X Y Z R F"),
    ("G82", "Drilling Cycle with Dwell",
     "Drill and dwell at bottom.",
     "G82 X10 Y10 Z-20 R2 P500 F100","X Y Z R P(ms dwell) F"),
    ("G83", "Peck Drilling",
     "Full retract peck drilling cycle.",
     "G83 X10 Y10 Z-30 R2 Q5 F80","X Y Z R Q(peck depth) F"),
    ("G84", "Tapping Cycle",
     "Right-hand tapping canned cycle.",
     "G84 X10 Y10 Z-15 R2 F200","X Y Z R F"),
    ("G85", "Boring Cycle",
     "Boring cycle — no dwell, feed out.",
     "G85 X10 Y10 Z-10 R2 F50","X Y Z R F"),
    ("G86", "Boring Cycle Spindle Stop",
     "Boring cycle — stop spindle, rapid out.",
     "G86 X10 Y10 Z-10 R2 F50","X Y Z R F P"),
    ("G87", "Back Boring Cycle",
     "Back boring canned cycle.",
     "G87 X10 Y10 Z-10 R2 I2 J2 F50","X Y Z R I J F"),
    ("G89", "Boring Cycle with Dwell",
     "Boring cycle with dwell at bottom.",
     "G89 X10 Y10 Z-10 R2 P500 F50","X Y Z R P F"),
    ("G98", "Canned Cycle Return Initial",
     "After canned cycle, return to initial Z level.",
     "G98","None"),
    ("G99", "Canned Cycle Return R Level",
     "After canned cycle, return to R plane.",
     "G99","None"),
    ("M0",  "Program Stop",
     "Optional program stop — wait for operator.",
     "M0","None"),
    ("M1",  "Optional Stop",
     "Optional stop if switch enabled.",
     "M1","None"),
    ("M2",  "Program End",
     "End of program.",
     "M2","None"),
    ("M6",  "Tool Change",
     "Execute a tool change.",
     "M6 T2","T(tool number)"),
    ("M19", "Spindle Orient",
     "Orient spindle to angle (for ATC).",
     "M19 S0","S(angle)"),
    ("M66", "Wait for Input",
     "Wait for digital input pin to reach state.",
     "M66 P3 L3 Q10  ; wait pin 3 high up to 10s",
     "P(pin) E(analog) L(mode) Q(timeout s)"),
  ],

  # ─── DELTA PRINTERS ───────────────────────────────────
  "Delta": [
    ("M665", "Delta Configuration",
     "Set delta geometry: diagonal rod length, radius, height, segments.",
     "M665 L250 R111 H250 B100 X0 Y0 Z0 S100",
     "L(rod) R(radius) H(height) B(print radius) X Y Z(tower offsets) S(segments/s)"),
    ("M666", "Delta Endstop Adjustments",
     "Fine-tune tower endstop offsets for delta calibration.",
     "M666 X0.5 Y-0.3 Z-0.2","X Y Z — endstop offset mm"),
    ("G33",  "Delta Auto-Calibrate",
     "Automated delta calibration via probe.",
     "G33 P4 C0.02 V2",
     "P(probe points 3-10) C(precision) V(verbose) O(old-style)"),
    ("M208", "Set Axis Max",
     "Set maximum travel for each axis (delta uses for height).",
     "M208 X235 Y235 Z300","X Y Z (max mm)"),
  ],

  # ─── LINEAR ADVANCE ───────────────────────────────────
  "Linear Adv": [
    ("M900", "Linear Advance K-Factor",
     "Set Linear Advance pressure control K factor.\n"
     "K=0 disables. Typical: PLA 0.05–0.2, PETG 0.1–0.3, Flex 0.5–2.0",
     "M900 K0.1   ; PLA\nM900 K0     ; disable\nM900 T0 K0.15 ; tool 0",
     "K(factor) T(tool) L(legacy mode)"),
  ],

  # ─── INPUT SHAPING ────────────────────────────────────
  "Input Shape": [
    ("M593", "Input Shaping",
     "Set input shaping (resonance compensation) frequency and damping.\n"
     "Reduces ghosting/ringing artifacts. Requires accelerometer calibration.",
     "M593 F45.6 D0.15 X\nM593 F0     ; disable",
     "F(frequency Hz) D(damping) X Y (axis)"),
    ("M494", "Resonance Test",
     "Run automatic resonance frequency test (requires ADXL345).",
     "M494","None"),
  ],

}

