"""Built-in G-code workflow templates."""

TEMPLATES = {
  "3D Print — Start": [
    "G28                    ; home all axes",
    "G29                    ; auto bed level",
    "M420 S1                ; enable bed leveling",
    "G1 Z5 F3000            ; raise Z",
    "G1 X0 Y0 F3000         ; move to origin",
    "M109 S200              ; wait for hotend 200°C",
    "M190 S60               ; wait for bed 60°C",
    "G92 E0                 ; reset extruder",
    "G1 X0 Y20 Z0.3 F3000   ; approach start",
    "G1 X0 Y200 E25 F500    ; prime line",
    "G92 E0                 ; reset extruder again",
    "M117 Printing...       ; display message",
  ],
  "3D Print — End": [
    "M104 S0                ; hotend off",
    "M140 S0                ; bed off",
    "G91                    ; relative",
    "G1 Z10 F3000           ; raise Z",
    "G90                    ; absolute",
    "G28 X Y                ; home X/Y",
    "M84                    ; disable steppers",
    "M117 Print complete!",
  ],
  "BLTouch — Deploy & Probe": [
    "M280 P0 S160           ; BLTouch alarm release",
    "G4 P100",
    "M280 P0 S10            ; deploy pin",
    "G4 P100",
    "G30                    ; single probe at current XY",
    "M280 P0 S120           ; stow pin",
  ],
  "BLTouch — Full Bed Level": [
    "G28                    ; home all",
    "M280 P0 S160           ; alarm release",
    "G4 P500",
    "G29                    ; full mesh probe",
    "M420 S1                ; enable mesh",
    "M500                   ; save to EEPROM",
    "M117 Bed leveled!",
  ],
  "BLTouch — Set Z Offset": [
    "G28                    ; home all",
    "M851 X-44 Y-14 Z0      ; reset probe offset",
    "G1 X117 Y117 Z10 F3000 ; center of bed",
    "G30                    ; probe and get Z",
    "; M851 Z<value>         ; set measured offset",
    "M500                   ; save",
    "M503                   ; verify",
  ],
  "CNC — Milling Start": [
    "G21                    ; mm units",
    "G90                    ; absolute",
    "G17                    ; XY plane",
    "M5                     ; spindle off",
    "G28                    ; home",
    "G92 X0 Y0 Z0           ; zero at home",
    "M3 S12000              ; spindle CW 12000 RPM",
    "G4 S3                  ; wait 3s for spindle",
    "G0 Z5                  ; safe Z",
  ],
  "CNC — Milling End": [
    "M5                     ; spindle off",
    "M9                     ; coolant off",
    "G0 Z50                 ; raise Z",
    "G28 X Y                ; home X/Y",
    "M84                    ; disable steppers",
    "M117 Job complete",
  ],
  "Laser — Start (GRBL)": [
    "G21                    ; mm",
    "G90                    ; absolute",
    "M5                     ; laser off",
    "G28                    ; home",
    "G92 X0 Y0              ; zero here",
    "M3 S0                  ; laser ready",
    "G0 X0 Y0 F6000         ; go to start",
  ],
  "Laser — End (GRBL)": [
    "M5                     ; laser off",
    "G0 X0 Y0               ; home position",
    "M9                     ; air off",
    "M84                    ; disable steppers",
  ],
  "PID Autotune — Hotend": [
    "M303 E0 S200 C8 U1     ; tune hotend at 200°C x8",
    "; result prints as M301 P.. I.. D..",
    "M500                   ; save when done",
  ],
  "PID Autotune — Bed": [
    "M303 E-1 S60 C8 U1     ; tune bed at 60°C x8",
    "; result prints as M304 P.. I.. D..",
    "M500",
  ],
  "Delta — Calibrate": [
    "G28                    ; home all towers",
    "G33 P4 C0.02 V2        ; auto calibrate",
    "M500                   ; save",
    "G28                    ; re-home",
    "M114                   ; verify position",
  ],
  "TMC — Sensorless Homing Setup": [
    "M914 X63 Y63           ; set stall sensitivity",
    "M569 S1 X Y            ; enable stealthchop if needed",
    "M500",
    "G28                    ; test homing",
    "M122                   ; check TMC report",
  ],
  "Filament Change Mid-Print": [
    "M600                   ; pause for filament change",
    "; (machine parks, unloads, waits)",
    "; load new filament on LCD prompt",
    "; machine purges and resumes",
  ],
  "Linear Advance Calibration": [
    "M900 K0                ; disable first",
    "M900 K0.1              ; test value",
    "; print calibration tower",
    "M900 K0.05             ; adjust",
    "M500                   ; save best value",
  ],
  "Mesh Leveling — Manual": [
    "G28",
    "M420 S0                ; disable leveling",
    "G29 S0                 ; start manual mesh",
    "; use LCD to adjust each point",
    "M420 S1                ; enable result",
    "M500",
  ],
  "Probe Accuracy Test": [
    "G28",
    "M48 P10 X100 Y100 V2 E L2  ; 10 probes, verbose",
    "; check Std Dev in output",
  ],
}

